CREATE DATABASE PIZZAHUT;

CREATE TABLE ORDERS(
ORDER_ID INT NOT NULL,
ORDER_DATE DATE NOT NULL,
ORDER_TIME TIME NOT NULL,
PRIMARY KEY(ORDER_ID));

CREATE TABLE ORDERS_DETAILS(
ORDER_DETAILS_ID INT NOT NULL,
ORDER_ID INT NOT NULL,
PIZZA_ID TEXT NOT NULL,
QUANTITY INT NOT NULL,
PRIMARY KEY(ORDER_DETAILS_ID));

-- Retrieve the total number of orders placed.
SELECT COUNT(ORDER_ID) AS TOTAL_ORDERS FROM ORDERS;

-- Calculate the total revenue generated from pizza sales.
SELECT ROUND(SUM(OD.QUANTITY*P.PRICE),2)AS TOTAL_REVENUE
FROM ORDERS_DETAILS AS OD
JOIN PIZZAS AS P
ON OD.PIZZA_ID=P.PIZZA_ID;

-- Identify the highest-priced pizza.
SELECT PT.NAME,P.PRICE AS HIGHEST_PRICED
FROM PIZZAS AS P
JOIN PIZZA_TYPES AS PT
ON P.PIZZA_TYPE_ID=PT.PIZZA_TYPE_ID
ORDER BY PRICE DESC
LIMIT 1;

-- Identify the most common pizza size ordered.
SELECT COUNT(OD.ORDER_DETAILS_ID) AS ORDER_COUNT,P.SIZE
FROM ORDERS_DETAILS AS OD
JOIN PIZZAS AS P
ON OD.PIZZA_ID=P.PIZZA_ID
GROUP BY P.SIZE
ORDER BY ORDER_COUNT DESC
LIMIT 1;

-- List the top 5 most ordered pizza types along with their quantities.
SELECT PT.NAME,SUM(OD.QUANTITY) AS TOTAL_QUANTITY
FROM PIZZA_TYPES AS PT
JOIN PIZZAS AS P
ON PT.PIZZA_TYPE_ID=P.PIZZA_TYPE_ID
JOIN ORDERS_DETAILS AS OD
ON OD.PIZZA_ID=P.PIZZA_ID
GROUP BY PT.NAME
ORDER BY TOTAL_QUANTITY DESC
LIMIT 5;

-- Join the necessary tables to find the total quantity of each pizza category ordered.
SELECT CATEGORY,SUM(OD.QUANTITY) AS TOTAL_QUANTITY
FROM PIZZA_TYPES AS PT
JOIN PIZZAS AS P
ON PT.PIZZA_TYPE_ID=P.PIZZA_TYPE_ID
JOIN ORDERS_DETAILS AS OD
ON OD.PIZZA_ID=P.PIZZA_ID
GROUP BY PT.CATEGORY
ORDER BY TOTAL_QUANTITY DESC
;

-- Determine the distribution of orders by hour of the day.
SELECT HOUR(ORDER_TIME) AS HOUR_DAY,COUNT(ORDER_ID) AS TOTAL_ORDER
FROM ORDERS
GROUP BY HOUR_DAY
ORDER BY TOTAL_ORDER DESC;

-- Join relevant tables to find the category-wise distribution of pizzas.
SELECT CATEGORY,COUNT(NAME) FROM PIZZA_TYPES
GROUP BY CATEGORY;

-- Group the orders by date and calculate the average number of pizzas ordered per day.
WITH AVG_PIZZA AS(
SELECT DATE(ODR.ORDER_DATE) AS DATE , SUM(OD.QUANTITY) AS QUANTITY
FROM ORDERS AS ODR
JOIN ORDERS_DETAILS AS OD
ON ODR.ORDER_ID=OD.ORDER_ID
GROUP BY DATE
)
SELECT AVG(QUANTITY) AS AVG_PIZZAS_SOLD_PER_DAY
FROM AVG_PIZZA;

-- Determine the top 3 most ordered pizza types based on revenue.
SELECT PT.NAME,SUM(OD.QUANTITY*P.PRICE) AS REVENUE
FROM PIZZA_TYPES AS PT
JOIN PIZZAS AS P
ON PT.PIZZA_TYPE_ID=P.PIZZA_TYPE_ID
JOIN ORDERS_DETAILS AS OD
ON OD.PIZZA_ID=P.PIZZA_ID
GROUP BY PT.NAME
ORDER BY REVENUE DESC 
LIMIT 3;

-- Calculate the percentage contribution of each pizza type to total revenue.
-- WITH SUBQUERY
SELECT PT.CATEGORY,ROUND(SUM(OD.QUANTITY*P.PRICE)/(SELECT SUM(OD.QUANTITY*P.PRICE) AS TOTAL_SALES
FROM ORDERS_DETAILS AS OD
JOIN PIZZAS AS P
ON OD.PIZZA_ID=P.PIZZA_ID)*100,2) AS REVENUE
FROM PIZZA_TYPES AS PT
JOIN PIZZAS AS P
ON PT.PIZZA_TYPE_ID=P.PIZZA_TYPE_ID
JOIN ORDERS_DETAILS AS OD
ON OD.PIZZA_ID=P.PIZZA_ID
GROUP BY PT.CATEGORY
ORDER BY REVENUE DESC;

-- OR
-- WITH CTE
WITH PIZZA_REVENUE AS
(
SELECT PT.CATEGORY,SUM(OD.QUANTITY*P.PRICE) AS REVENUE
FROM PIZZA_TYPES AS PT
JOIN PIZZAS AS P 
ON PT.PIZZA_TYPE_ID=P.PIZZA_TYPE_ID
JOIN ORDERS_DETAILS AS OD
ON OD.PIZZA_ID=P.PIZZA_ID
GROUP BY PT.CATEGORY
),
TOTAL_REVENUE AS(
SELECT SUM(REVENUE) AS TOTAL_REVENUE
FROM  PIZZA_REVENUE
)
SELECT PR.CATEGORY,ROUND((PR.REVENUE/TR.TOTAL_REVENUE)*100,2) AS PERCENTAGE_CONTRIBUTION
FROM PIZZA_REVENUE AS PR
CROSS JOIN TOTAL_REVENUE AS TR
ORDER BY PERCENTAGE_CONTRIBUTION DESC;

-- Analyze the cumulative revenue generated over time.
WITH ROLLING_TOTAL AS(
SELECT ODR.ORDER_DATE AS DATE,SUM(OD.QUANTITY*P.PRICE) AS REVENUE
FROM ORDERS AS ODR
JOIN ORDERS_DETAILS AS OD
ON ODR.ORDER_ID=OD.ORDER_ID
JOIN PIZZAS AS P
ON OD.PIZZA_ID=P.PIZZA_ID
GROUP BY DATE
ORDER BY 1
)
SELECT DATE,REVENUE,SUM(REVENUE) OVER(ORDER BY DATE) AS ROLLING_TOTAL
FROM ROLLING_TOTAL;

-- Determine the top 3 most ordered pizza types based on revenue for each pizza category.
SELECT CATEGORY,NAME,REVENUE FROM
(SELECT CATEGORY,NAME,REVENUE,RANK() OVER(PARTITION BY CATEGORY ORDER BY REVENUE DESC)AS RN
FROM 
(SELECT PT.CATEGORY,PT.NAME,SUM(OD.QUANTITY*P.PRICE) AS REVENUE
FROM PIZZA_TYPES AS PT
JOIN PIZZAS AS P
ON PT.PIZZA_TYPE_ID=P.PIZZA_TYPE_ID
JOIN ORDERS_DETAILS AS OD
ON OD.PIZZA_ID=P.PIZZA_ID
GROUP BY PT.CATEGORY,PT.NAME) AS A)AS B
WHERE RN<=3;

 -- OR 
 -- WITH CTE
 
 WITH REVENUE_CTE AS(
 SELECT PT.CATEGORY AS CATEGORY,PT.NAME AS PIZZA_NAME,SUM(OD.QUANTITY*P.PRICE) AS REVENUE
FROM PIZZA_TYPES AS PT
JOIN PIZZAS AS P
ON PT.PIZZA_TYPE_ID=P.PIZZA_TYPE_ID
JOIN ORDERS_DETAILS AS OD
ON OD.PIZZA_ID=P.PIZZA_ID
GROUP BY PT.CATEGORY,PT.NAME
),
RANKED_CTE AS(
SELECT CATEGORY,PIZZA_NAME ,REVENUE,
RANK() OVER(PARTITION BY CATEGORY ORDER BY REVENUE DESC) AS RN
FROM REVENUE_CTE
)
SELECT CATEGORY,PIZZA_NAME,REVENUE
FROM RANKED_CTE
WHERE RN<=3;
 













